
package nl.hu.fnt.maarten.wsInterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dataServiceInterface", targetNamespace = "http://nl.hu.fnt/dataservice/message")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataServiceInterface {


    /**
     * 
     * @param postRequest
     * @return
     *     returns nl.hu.fnt.maarten.wsInterface.Response
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://nl.hu.fnt/dataservice/response", partName = "response")
    public Response postData(
        @WebParam(name = "postRequest", targetNamespace = "http://nl.hu.fnt/dataservice/postRequest", partName = "postRequest")
        PostRequest postRequest)
        throws Fault
    ;

    /**
     * 
     * @param getRequest
     * @return
     *     returns nl.hu.fnt.maarten.wsInterface.Response
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://nl.hu.fnt/dataservice/response", partName = "response")
    public Response getData(
        @WebParam(name = "getRequest", targetNamespace = "http://nl.hu.fnt/dataservice/getRequest", partName = "getRequest")
        GetRequest getRequest)
        throws Fault
    ;

}
