
package nl.hu.fnt.maarten.wsInterface;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "dataService", targetNamespace = "http://nl.hu.fnt/dataservice/message", wsdlLocation = "file:/C:/Users/maart_000/Documents/School/Opleiding_HBO-ICT/2017/blok%20C/000SOAP-data-service/web/wsdl/dataService.wsdl")
public class DataService
    extends Service
{

    private final static URL DATASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(nl.hu.fnt.maarten.wsInterface.DataService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = nl.hu.fnt.maarten.wsInterface.DataService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/maart_000/Documents/School/Opleiding_HBO-ICT/2017/blok%20C/000SOAP-data-service/web/wsdl/dataService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/maart_000/Documents/School/Opleiding_HBO-ICT/2017/blok%20C/000SOAP-data-service/web/wsdl/dataService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATASERVICE_WSDL_LOCATION = url;
    }

    public DataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataService() {
        super(DATASERVICE_WSDL_LOCATION, new QName("http://nl.hu.fnt/dataservice/message", "dataService"));
    }

    /**
     * 
     * @return
     *     returns DataServiceInterface
     */
    @WebEndpoint(name = "WS-Port")
    public DataServiceInterface getWSPort() {
        return super.getPort(new QName("http://nl.hu.fnt/dataservice/message", "WS-Port"), DataServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataServiceInterface
     */
    @WebEndpoint(name = "WS-Port")
    public DataServiceInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nl.hu.fnt/dataservice/message", "WS-Port"), DataServiceInterface.class, features);
    }

}
